### PR TITLE
Give more specific errors when rcedit cannot set an icon

### PR DESCRIPTION
**Pull request by malept**
In the Electron Packager and Electron Forge issue trackers, one of the common issues that pops up is people asking what's going on when the build process errors out with `rcedit.exe failed with exit code 1. Fatal error: Unable to set icon`. This pull request attempts to give more details as to why setting the icon failed.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@ckerr I don't think `rcedit` has access to that macro 🤔

**Comment by malept** [comment]
I'd be happy to use a more idiomatic way to deal with errors, but my knowledge of the C++/Windows ecosystem is minimal, so assistance would be much appreciated.

**Comment by malept** [comment]
Thanks @zcbenz. When can we expect a new release of `rcedit` and `node-rcedit`?

**Comment by zcbenz** [comment]
@malept Soon.

**Pull request merged**
